apiVersion: v2
publisher: RedHat
name: Java-Smoke-Test-Plugin
version: 0.0.1
type: Theia plugin
displayName: Java Smoke Test Plugin
title: Java-Smoke-Test-Plugin
description: This plug-in runs Java tests against vscode-java inside of your workspace
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/che-incubator/che-java-tests
category: Language
firstPublicationDate: "2020-08-20"
spec:
  extensions:
    - https://github.com/svor/che-java-tests/blob/sv/tests/che_java_test_theia_plugin.theia
